import config
class CreateBatchFiles():
    def get_batch(self, prompt, batch_name, timestring):
        filetxt = \
            {
                "W": config.VIDEO_WIDTH,
                "H": config.VIDEO_HEIGHT,
                "tiling": False,
                "restore_faces": False,
                "seed": config.SEED,
                "sampler": "Euler a",
                "seed_resize_from_w": 0,
                "seed_resize_from_h": 0,
                "steps": 25,
                "ddim_eta": 0.0,
                "save_settings": True,
                "save_sample_per_step": False,
                "batch_name": f"{batch_name}",
                "seed_behavior": "iter",
                "seed_iter_N": 1,
                "use_init": False,
                "strength_0_no_init": True,
                "strength": config.STRENGTH,
                "init_image": None,
                "use_mask": False,
                "use_alpha_as_mask": False,
                "invert_mask": False,
                "overlay_mask": True,
                "mask_file": "https://deforum.github.io/a1/M1.jpg",
                "mask_contrast_adjust": 1.0,
                "mask_brightness_adjust": 1.0,
                "mask_overlay_blur": 4,
                "fill": 1,
                "full_res_mask": True,
                "full_res_mask_padding": 4,
                "reroll_blank_frames": "reroll",
                "reroll_patience": 10.0,
                "precision": "autocast",
                "timestring": f"{timestring}",
                "prompts": prompt,
                "positive_prompts": "",
                "negative_prompts": "",
                "outdir": f"/workspace/stable-diffusion-webui/outputs/img2img-images/{batch_name}",
                "animation_mode": f"{config.ANIMATION_MODE}",
                "max_frames": config.FRAME_COUNT,
                "border": "replicate",
                "angle": f"0:({config.ROTATION_ANGLE})",
                "zoom": f"0:({config.ZOOM_SPEED})",
                "translation_x": "0:(0)",
                "translation_y": "0:(0)",
                "translation_z": "0:(1.75)",
                "transform_center_x": "0:(0.5)",
                "transform_center_y": "0:(0.5)",
                "rotation_3d_x": "0:(0)",
                "rotation_3d_y": "0:(0)",
                "rotation_3d_z": "0:(0)",
                "enable_perspective_flip": False,
                "perspective_flip_theta": "0:(0)",
                "perspective_flip_phi": "0:(0)",
                "perspective_flip_gamma": "0:(0)",
                "perspective_flip_fv": "0:(53)",
                "noise_schedule": f"0: (0.065)",
                "strength_schedule": f"0: (0.65)",
                "contrast_schedule": "0: (1.0)",
                "cfg_scale_schedule": "0: (7)",
                "pix2pix_img_cfg_scale_schedule": "0:(1.5)",
                "enable_subseed_scheduling": False,
                "subseed_schedule": "0:(1)",
                "subseed_strength_schedule": "0:(0)",
                "enable_steps_scheduling": False,
                "steps_schedule": "0: (25)",
                "fov_schedule": "0: (70)",
                "aspect_ratio_schedule": "0: (1)",
                "aspect_ratio_use_old_formula": False,
                "near_schedule": "0: (200)",
                "far_schedule": "0: (10000)",
                "seed_schedule": "0:(s), 1:(-1), \"max_f-2\":(-1), \"max_f-1\":(s)",
                "enable_sampler_scheduling": False,
                "sampler_schedule": "0: (\"Euler a\")",
                "mask_schedule": "0: (\"{video_mask}\")",
                "use_noise_mask": False,
                "noise_mask_schedule": "0: (\"{video_mask}\")",
                "enable_checkpoint_scheduling": False,
                "checkpoint_schedule": "0: (\"model1.ckpt\"), 100: (\"model2.safetensors\")",
                "enable_clipskip_scheduling": False,
                "clipskip_schedule": "0: (2)",
                "enable_noise_multiplier_scheduling": True,
                "noise_multiplier_schedule": "0: (1.05)",
                "kernel_schedule": "0: (5)",
                "sigma_schedule": "0: (1.0)",
                "amount_schedule": "0: (0.1)",
                "threshold_schedule": "0: (0.0)",
                "color_coherence": f"{config.COLOR_COHERENCE}",
                "color_coherence_image_path": "",
                "color_coherence_video_every_N_frames": 1.0,
                "color_force_grayscale": False,
                "diffusion_cadence": "2",
                "optical_flow_cadence": "None",
                "cadence_flow_factor_schedule": "0: (1)",
                "optical_flow_redo_generation": "None",
                "redo_flow_factor_schedule": "0: (1)",
                "diffusion_redo": "0",
                "noise_type": "perlin",
                "perlin_octaves": 4,
                "perlin_persistence": 0.5,
                "use_depth_warping": True,
                "use_zoe_depth": False,
                "midas_weight": 0.2,
                "padding_mode": "border",
                "sampling_mode": "bicubic",
                "save_depth_maps": False,
                "video_init_path": "",
                "extract_nth_frame": 1,
                "extract_from_frame": 0,
                "extract_to_frame": -1,
                "overwrite_extracted_frames": False,
                "use_mask_video": False,
                "video_mask_path": "",
                "resume_from_timestring": False,
                "resume_timestring": f"{timestring}",
                "hybrid_generate_inputframes": False,
                "hybrid_generate_human_masks": "None",
                "hybrid_use_first_frame_as_init_image": True,
                "hybrid_motion": "None",
                "hybrid_motion_use_prev_img": False,
                "hybrid_flow_method": "RAFT",
                "hybrid_composite": "None",
                "hybrid_use_init_image": False,
                "hybrid_comp_mask_type": "None",
                "hybrid_comp_mask_inverse": False,
                "hybrid_comp_mask_equalize": "None",
                "hybrid_comp_mask_auto_contrast": False,
                "hybrid_comp_save_extra_frames": False,
                "hybrid_comp_alpha_schedule": "0:(0.5)",
                "hybrid_flow_factor_schedule": "0:(1)",
                "hybrid_comp_mask_blend_alpha_schedule": "0:(0.5)",
                "hybrid_comp_mask_contrast_schedule": "0:(1)",
                "hybrid_comp_mask_auto_contrast_cutoff_high_schedule": "0:(100)",
                "hybrid_comp_mask_auto_contrast_cutoff_low_schedule": "0:(0)",
                "parseq_manifest": None,
                "parseq_use_deltas": True,
                "use_looper": False,
                "init_images": "{\n    \"0\": \"https://deforum.github.io/a1/Gi1.png\",\n    \"max_f/4-5\": \"https://deforum.github.io/a1/Gi2.png\",\n    \"max_f/2-10\": \"https://deforum.github.io/a1/Gi3.png\",\n    \"3*max_f/4-15\": \"https://deforum.github.io/a1/Gi4.jpg\",\n    \"max_f-20\": \"https://deforum.github.io/a1/Gi1.png\"\n}",
                "image_strength_schedule": "0:(0.75)",
                "blendFactorMax": "0:(0.35)",
                "blendFactorSlope": "0:(0.25)",
                "tweening_frames_schedule": "0:(20)",
                "color_correction_factor": "0:(0.075)",
                "skip_video_creation": False,
                "fps": 15,
                "make_gif": False,
                "delete_imgs": True,
                "add_soundtrack": "None",
                "soundtrack_path": "",
                "r_upscale_video": False,
                "r_upscale_model": "realesr-animevideov3",
                "r_upscale_factor": "x2",
                "r_upscale_keep_imgs": False,
                "store_frames_in_ram": False,
                "frame_interpolation_engine": "None",
                "frame_interpolation_x_amount": 2,
                "frame_interpolation_slow_mo_enabled": False,
                "frame_interpolation_slow_mo_amount": 2,
                "frame_interpolation_keep_imgs": False,
                "sd_model_name": "ProtoGen_X5.8-pruned-fp16.ckpt",
                "sd_model_hash": "d2089202",
                "deforum_git_commit_id": "83235961 (Sun Apr 23 10:40:12 2023)"
            }
        return filetxt